export const filterFields = [
    'poiName',
    'tweetLang',
    'country',
    'sentiment',
    'timestamp',
    'mentions',
    'replyCount',
    'showOnlyPoi',
    'showOnlyReplies',
    'showTweetsWithLinks',
    'hashtags',
]
export const arrayFields = [
    'poiName',
    'tweetLang',
    'country',
    'sentiment',
    'timestamp',
]

export const poiList = [
    'lopezobrador_',
    'SSalud_mx',
    'PMOIndia',
    'EPN',
    'RahulGandhi',
    'narendramodi',
    'VP',
    'rashtrapatibhvn',
    'CDCgov',
    'COVIDNewsByMIB',
    'DrEricDing',
    'CDCDirector',
    'MyGovHindi',
    'SpeakerPelosi',
    'COFEPRIS',
    'HLGatell',
    'MoHFW_INDIA',
    'DrTomFrieden',
    'NIH',
    'ArvindKejriwal',
    'AmitShah',
    'EricTopol',
    'KamalaHarris',
    'nycHealthy',
    'POTUS',
    'JoeBiden',
    'ICMRDELHI',
    'SaludEdomex',
    'MarkoCortes',
    'RicardoMonrealA',
    'BarackObama',
    'XavierBecerra',
    'alfredodelmazo',
    'redaccionmedica',
    'ewarren',
    'm_ebrard',
    'HillaryClinton',
    'Claudiashein',
    'HillsboroughFL',
    'ShashiTharoor',
    'drharshvardhan',
    'myogiadityanath',
    'ECDOH',
    'PiyushGoyal',
    'FelipeCalderon',
    'mansukhmandviya',
    'BJPIndia',
    'smritiirani',
    'Mzavalagc',
    'GovKathyHochul',
    'MIB_India',
]

export const sentimentVsLabel = {
    positive: 'Positive',
    negative: 'Negative',
    neutral: 'Neutral',
}
export const sentimentVsColor = {
    positive: '#67c23a',
    negative: '#f56c6c',
    neutral: '#909399',
}
export const countryVsColor = {
    India: 'rgb(201, 36, 39)',
    Mexico: 'rgb(215, 0, 38)',
    USA: 'rgb(0, 82, 180)',
}

export const langVsLabel = { en: 'English', es: 'Spanish', hi: 'Hindi' }
